# ============================================================
# ArgoCD Application: backend
# Wave 1 — sau khi infra (Prometheus) đã ready
# Trỏ tới backend/k8s/ chứa: Rollout, AnalysisTemplate, Services
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/NguyenDinhThi-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/lab-final/backend/k8s         # trỏ tới folder manifest thật của backend
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
