# ============================================================
# ArgoCD Application: infra
# Wave 0 — deploy monitoring infra (PrometheusRule, OTel, ServiceMonitor)
# TRƯỚC khi backend/frontend được deploy
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/NguyenDinhThi-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/lab-final/infra/k8s           # trỏ tới folder manifest thật của infra
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
