apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-email-eso
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-store-monitoring
    kind: SecretStore
  target:
    name: alertmanager-email
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: prod/alertmanager/email
