apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: demo
data:
  api.json: |
    {
      "status": "success",
      "message": "Kết nối thành công tới Backend API!",
      "database": "connected",
      "timestamp": "2026-06-11T11:00:00Z"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: backend-api-vol
              mountPath: /usr/share/nginx/html/api.json
              subPath: api.json
      volumes:
        - name: backend-api-vol
          configMap:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: backend
