apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/TechX-Corp/xbrain-learners.git'
    targetRevision: HEAD
    path: cloud/w9/day-a  # Path to Kubernetes manifests in the repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
