apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-store
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      # Dùng EC2 Instance Profile (IAM Role) — không cần static credentials
      # EC2 tự xác thực với AWS thông qua metadata service
      auth:
        jwt:
          serviceAccountRef:
            name: default
