apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-store
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      # Không cần auth block → ESO dùng EC2 Instance Profile tự động
      # Credential chain: EC2 IMDS → IAM Role → Secrets Manager
